globals:
  # local_base_file_path: /Users/uirja/OneDrive/Personal Files/CS Projects/outage-data-scraper/raw_data # for joshua
  LOCAL_FILE_BASE_PATH: /Users/xuanedx1/github/outage-data-scraper/data/s3

providers:
  - name: Amicalola EMC
    state: ga
    layout: 1
    type: o
  - name: Canoochee EMC
    state: ga
    layout: 1
    type: o
  - name: Central Georgia EMC
    state: ga
    layout: 1
    type: o
  - name: Dalton Utility
    state: ga
    layout: 1
    type: o
  - name: Diverse Power
    state: ga
    layout: 1
    type: o
  - name: Excelsior EMC
    state: ga
    layout: 1
    type: o
  - name: Flint EMC
    state: ga
    layout: 1
    type: o
  - name: Grady EMC
    state: ga
    layout: 1
    type: o
  - name: Jefferson Energy Cooperative
    state: ga
    layout: 1
    type: o
  - name: North Georgia EMC
    state: ga
    layout: 1
    type: o
  - name: Okefenoke REMC
    state: ga
    layout: 1
    type: o
  - name: Satilla REMC
    state: ga
    layout: 1
    type: o
  - name: Washington EMC
    state: ga
    layout: 1
    type: o
  - name: investor_owned
    state: ca
    layout: investor
    type: o
  - name: Coastal Electric Cooperation
    state: ga
    layout: 3
    type: o
  - name: Irwin EMC
    state: ga
    layout: 3
    type: o
  - name: Middle Georgia EMC
    state: ga
    layout: 3
    type: o
  - name: Upson EMC
    state: ga
    layout: 3
    type: o
  - name: Bluebonnet Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Bryan Texas Utilities
    state: tx
    layout: 8
    type: o
  - name: Bowie-Cass Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: College Station Utilities
    state: tx
    layout: 8
    type: o
  - name: Farmers Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Guadalupe Valley Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Mid-South Electric Coop Association
    state: tx
    layout: 8
    type: o
  - name: New Braunfels Utilities
    state: tx
    layout: 8
    type: o
  - name: North Plains Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Nueces Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Taylor Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Trinity Valley Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Wood County Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Blueridge Mountain EMC
    state: ga 
    layout: 2
    type: o
  - name: Tri-County EMC  # I ASSUMED "TRI-COUNTT" WAS A TYPO AND CHANGED IT TO TRI-COUNTY
    state: ga
    layout: 2
    type: o
  - name: United Coop Services, Inc.
    state: tx
    layout: 17
    type: o
  - name: Walton EMC
    state: ga
    layout: 11
    type: o
  - name: Tri-State EMC
    state: ga
    layout: 11
    type: o
  - name: Oconee EMC
    state: ga
    layout: 11
    type: o
  - name: Mitchell EMC
    state: ga
    layout: 11
    type: o
  - name: Wise Electric Coop, Inc.
    state: tx
    layout: 12
    type: o
  - name: Houston County Electric Coop, Inc.
    state: tx
    layout: 12
    type: o
  - name: Cherokee County Electric Coop Association
    state: tx
    layout: 12
    type: o
  - name: Comanche Electric Coop
    state: tx
    layout: 16
    type: o
  - name: Southwestern Electric Coop, Inc.
    state: tx
    layout: 16
    type: o