globals:
  local_base_file_path: /Users/xuanedx1/github/outage-data-scraper/data/s3
  # local_base_file_path: /Users/uirja/OneDrive/Personal Files/CS Projects/outage-data-scraper/raw_data # for joshua
providers:
  - name: Amicalola EMC
    state: ga
    layout: 1
    type: o
  - name: Canoochee EMC
    state: ga
    layout: 1
    type: o
  - name: Central Georgia EMC
    state: ga
    layout: 1
    type: o
  - name: Dalton Utility
    state: ga
    layout: 1
    type: o
  - name: Diverse Power
    state: ga
    layout: 1
    type: o
  - name: Excelsior EMC
    state: ga
    layout: 1
    type: o
  - name: Flint EMC
    state: ga
    layout: 1
    type: o
  - name: Grady EMC
    state: ga
    layout: 1
    type: o
  - name: Jefferson Energy Cooperative
    state: ga
    layout: 1
    type: o
  - name: North Georgia EMC
    state: ga
    layout: 1
    type: o
  - name: Okefenoke REMC
    state: ga
    layout: 1
    type: o
  - name: Satilla REMC
    state: ga
    layout: 1
    type: o
  - name: Washington EMC
    state: ga
    layout: 1
    type: o
  - name: Bluebonnet Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Bryan Texas Utilities
    state: tx
    layout: 8
    type: o
  - name: Bowie-Cass Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: College Station Utilities
    state: tx
    layout: 8
    type: o
  - name: Farmers Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Guadalupe Valley Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Mid-South Electric Coop Association
    state: tx
    layout: 8
    type: o
  - name: New Braunfels Utilities
    state: tx
    layout: 8
    type: o
  - name: North Plains Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Nueces Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Taylor Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Trinity Valley Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Wood County Electric Coop, Inc.
    state: tx
    layout: 8
    type: o
  - name: Blueridge Mountain EMC
    state: ga 
    type: 2
    name: o
  - name: Tri-County EMC  # I ASSUMED "TRI-COUNTT" WAS A TYPO AND CHANGED IT TO TRI-COUNTY
    state: ga
    type: 2
    name: o
  - name: United Coop Services, Inc.
    state: tx
    type: 17
    name: o
  - name: Walton EMC
    state: ga
    layout: 11
    type: o
  - name: Tri-State EMC
    state: ga
    layout: 11
    type: o
  - name: Oconee EMC
    state: ga
    layout: 11
    type: o
  - name: Mitchell EMC
    state: ga
    layout: 11
    type: o
  - name: Wise Electric Coop, Inc.
    state: tx
    layout: 12
    type: o
  - name: Houston County Electric Coop, Inc.
    state: tx
    layout: 12
    type: o
  - name: Cherokee County Electric Coop Association
    state: tx
    layout: 12
    type: o


